# Generated by Django 4.1 on 2022-08-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choiceapp', '0002_pollques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.CharField(max_length=10)),
                ('ans', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('t_time', models.CharField(max_length=15)),
                ('t_date', models.CharField(max_length=20)),
                ('note', models.TextField(max_length=280)),
            ],
            options={
                'db_table': 'poll_sol',
            },
        ),
    ]
